version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2020!"
    ports:
      - "5432:5432"
    volumes:
      - /home/postgres:/var/lib/postgresql/data
    networks:
      - postgres-network-compose
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ferbs89@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Postgres2020!"
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-network-compose

networks: 
  postgres-network-compose:
    driver: bridge